### ISSUE TITLE
when the es server cannot connect,gave some debug info,now is error info?

### ISSUE THREAD

**Issue by indexlang** [Elders/log4net.Appender.ElasticSearch#3] opened 2019-08-05 14:48 UTC

**Comment by AlexPlom** [comment] 2019-08-06 08:18
Greetings, can you provide more information and any steps to reproduce locally? I also don't understand exactly what the issue is

**Comment by AlexPlom** [comment] 2019-08-13 07:54
I will be closing this issue do to lack of description and activity. Please re-open and assign me here if you see fit.

**Closed as completed by AlexPlom** 2019-08-13 07:54 UTC
